"""empty message

Revision ID: 4c0826e8f6ee
Revises: 583ea2ab43f2
Create Date: 2020-01-15 19:20:33.634868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c0826e8f6ee'
down_revision = '583ea2ab43f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    #<Ajitesh> Add completed to the exiting data
    # ### end Alembic commands ###
    op.execute('UPDATE todos SET completed=False WHERE completed IS NULL;')
    op.alter_column('todos', 'completed', nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
